### PR TITLE
#38: ArrayTransformation might fail if column name us a number

### LINKED ISSUE #38: ArrayTransformation might fail if column name us a number
## Describe the bug
The method `ArrayTransformations.arrCol` does not consider the possibility of a column having a numeric name. Spark Execution then will fail.

## Expected behavior
Take numeric name columns into account.

### PR DESCRIPTION
**Pull request by benedeki**
* method `ArrayTransformations.arrCol` renamed to `StdSchemaUtils.evaluateColumnName`
* added unit tests for the method

Closes #38

### CODE REVIEW

File: src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala [hunk 1]
```diff
@@ -46,10 +51,32 @@ object StdSchemaUtils {
         .replace('.', '_')
   }
 
+  def evaluateColumnName(columnName: String): Column = {
```
Comment (benedeki) [inline src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala:54]: Might this function be worth to be placed in _Spark Commons_?
On the other hand, so far, it's used only in `ArrayTransformations`. 🤔

Comment (Zejnilovic) [reply src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala:54]: It's good enough to be in _spark commons_. If you have time and energy go ahead

File: src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala [hunk 2]
```diff
@@ -46,10 +51,32 @@ object StdSchemaUtils {
...
+    def segmentToColumn(colFnc: String => Column, columnSegment: String): Column = { // TODO
```
Comment (miroslavpojer) [inline src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala:55]: Forgot note "// TODO" ?

File: src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala [hunk 3]
```diff
@@ -46,10 +51,32 @@ object StdSchemaUtils {
         .replace('.', '_')
   }
 
+  def evaluateColumnName(columnName: String): Column = {
+    def segmentToColumn(colFnc: String => Column, columnSegment: String): Column = {
+      val PatternForSubfield = """^(.+)\[(.+)]$""".r
```
Comment (lsulak) [inline src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala:56]:
```suggestion
      val PatternForSubfield = """^(.+)\[(.+)\]$""".r
```
❓

Comment (Zejnilovic) [reply src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala:56]: `]` has to be escaped only inside the character classes.

Comment (jakipatryk) [reply src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala:56]: Both seem to be working, but the one proposed by @lsulak seems more natural to me. Actually I'm surprised that `]` doesn't have to be escaped.

File: src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala (hunk 1 above)
Comment (benedeki) [reply src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala:54]: Will put it there later. Have another candidate in working.
They can both be part of the new Spark Commons version.

File: src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala (hunk 3 above)
Comment (lsulak) [reply src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala:56]: If I understood you correctly, then there is still one improvement possible (thanks for the explanation Sasa about the character classes - it makes sense):

```suggestion
      val PatternForSubfield = """^(.+)[(.+)]$""".r
```

Exactly, why to complicate it by having it for open bracket and not for the closing one?

Comment (benedeki) [reply src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala:56]: Well the first escape is necessary I believe. Otherwise `[` will act as start of list characters to match instead of the literal `[`. 🤔

Comment (lsulak) [reply src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala:56]: Your arguments & facts I think more than satisfied (i.e. destroyed :D ) my original questions. Makes sense, of course!

File: src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala (hunk 1 above)
Comment (benedeki) [reply src/main/scala/za/co/absa/standardization/schema/StdSchemaUtils.scala]: Done

**Review by miroslavpojer — COMMENTED** [review]
All test Passing. Code read.

**Review by jakipatryk — APPROVED** [review]
LGTM (just checked the code)
