### PR TITLE
#65 Fix default record id prefix being null

### LINKED ISSUE #65: RecordId column should not be null_record_id
## Describe the bug
When using the default metadata configuration, the record id column is called `null_record_id` instead of `standardization_record_id`, as it was probably intended.

## To Reproduce
This can be reproduced with version 0.2.1
Steps to reproduce the behavior OR commands run:
1. Execute `standardizedDf = Standardization.standardize(df, schema)` with any dataframe and schema. (For example, execute the "Test standardizing a CSV with special columns when error column has correct type")
2. Inspect the schema of `standardizedDf`
3. Observe the column `null_record_id`

## Expected behavior
The column should be called `standardization_record_id`

## Additional context
Looks like the `prefix` is not initialized in `MetadataColumnsConfig`. Probably the idea was to have it initialized in `DefaultMetadataColumnsConfig`

### PR DESCRIPTION
**Pull request by Zejnilovic**
Closes #65 

Changed to `def`s so we don't have a race condition on init of the `val`s.

### CODE REVIEW

**Comment by yruslan** [comment]
Looks good. I'd just suggest to add a regression test that fails with the old code and succeeds with the new code. 

Cause right now it is not obvious that the fix works.

**Comment by Zejnilovic** [comment]
> Looks good. I'd just suggest to add a regression test that fails with the old code and succeeds with the new code.
> 
> Cause right now it is not obvious that the fix works.

Should be fixed now.

File: src/test/scala/za/co/absa/standardization/config/MetadataColumnsConfigTest.scala [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+    assert(conf.metadataColumns.recordIdStrategy == RecordIdGeneration.IdType.TrueUuids)
+    assert(conf.metadataColumns.reportDateFormat == "yyyy-MM-dd")
+    assert(conf.metadataColumns.infoDateColumn == "standardization_info_date")
+    assert(conf.metadataColumns.infoDateColumnString == "standardization_info_date_string")
+    assert(conf.metadataColumns.infoVersionColumn == "standardization_info_version")
+    assert(conf.metadataColumns.recordId == "standardization_record_id")
+
+    assert(conf.typeDefaults == CommonTypeDefaults)
+
+
```
Comment (yruslan) [inline src/test/scala/za/co/absa/standardization/config/MetadataColumnsConfigTest.scala:47]: Extra spaces

**Review by yruslan — APPROVED** [review]
Looks good to me

**Review by kevinwallimann — DISMISSED** [review]
lgtm

**Review by yruslan — APPROVED** [review]

File: src/main/scala/za/co/absa/standardization/config/MetadataColumnsConfig.scala [hunk 2]
```diff
@@ -23,9 +23,10 @@ trait MetadataColumnsConfig {
   val prefix: String
   val recordIdStrategy: RecordIdGeneration.IdType
 
-  val infoDateColumn = prefix + "_info_date"
-  val infoDateColumnString = s"${infoDateColumn}_string"
   val reportDateFormat = "yyyy-MM-dd"
-  val infoVersionColumn = prefix + "_info_version"
-  val recordId = prefix + "_record_id"
+
```
Comment (benedeki) [inline src/main/scala/za/co/absa/standardization/config/MetadataColumnsConfig.scala:27]: I would change all the `val` to `def`, as it's customary for traits (`def` can be overridden by a `val` or `def`, `val` can be overridden by `val` only).
Or at least those, that are abstract. To avoid potential similar problems, to the one this PR fixes.

**Review by benedeki — APPROVED** [review]
- [x] code reviewed
- [ ] pulled
- [ ] built
- [ ] run
